name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY }}
      REACT_APP_AUTH_DOMAIN: ${{ secrets.REACT_APP_AUTH_DOMAIN }}
      REACT_APP_DATABASE_URL: ${{ secrets.REACT_APP_DATABASE_URL }}
      REACT_APP_PROJECT_ID: ${{ secrets.REACT_APP_PROJECT_ID }}
      REACT_APP_STORAGE_BUCKED: ${{ secrets.REACT_APP_STORAGE_BUCKED }}
      REACT_APP_MESSAGING_SENDER_SD: ${{ secrets.REACT_APP_MESSAGING_SENDER_SD }}
      REACT_APP_APP_ID: ${{ secrets.REACT_APP_APP_ID }}
      REACT_APP_MEASUREMENT_ID: ${{ secrets.REACT_APP_MEASUREMENT_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build:gh-pages

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
